# SimpleShopCore mods.toml file
modLoader="javafml"
loaderVersion="[47,)"
license="LGPL3.0"

[[mods]]
modId="simpleshopcore"
version="2.0.0"
displayName="SimpleShopCore"
authors="y271727uy"
description='''A shop mod for Minecraft'''

[[dependencies.simpleshopcore]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.simpleshopcore]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

